feat: Implement Lazy Loading for Header Parsing to Avoid Unnecessary Validation
serverpod/relic pull request #17
Opened 2024-12-17 09:02 UTC by klkucaj

### **PR Description**  
This PR implements lazy loading for header parsing and validation. Headers are now parsed and validated only when explicitly accessed by the request handler, improving performance and avoiding unnecessary validation for unused headers.  

Closes #10

2025-01-09 13:00 UTC, SandPod commented on lib/src/relic_server.dart
> +    } on InvalidHeaderException catch (error) {
Question: This exception is exported right?

I'm inspecting the first commit; we could probably have added tests that validate that the changes in that commit work if the exception was exported.

2025-01-09 13:01 UTC, SandPod commented on lib/src/relic_server.dart
> +      return Response.badRequest(
Question: Should't we create a log entry here as well? We could end up here because someone copied the response headers right?

2025-01-09 13:05 UTC, SandPod commented on lib/src/headers/headers.dart
> +    // Failed headers to parse
Suggestion: Should we rename this to `invalidHeaders`?  This should be done in another PR if we should to it.

2025-01-09 13:09 UTC, SandPod commented on lib/src/headers/headers.dart
> +  }) {
Suggestion: Rename to `_LazyInit.from` and replace the named named parameter with a mandatory parameter, this factory can simply take a single argument.

2025-01-09 13:10 UTC, SandPod commented on lib/src/headers/headers.dart
> +  factory _LazyInit.value({
Suggestion: rename to `_LazyInit.withValue` and replace the named parameter with a single mandatory argument.

2025-01-09 13:14 UTC, SandPod commented on test/headers/headers_test_utils.dart
> +        // complete.
Suggestion: Remove comment, this is self-explanatory from the variable name.

2025-01-09 13:15 UTC, SandPod commented on lib/src/headers/headers.dart
> +    for (var entry in booleanHeaders.entries) {
Question: Was this missing before? Should we have a test that validates that we actually add all headers?

2025-01-09 13:17 UTC, SandPod commented on test/headers/typed_headers/transfer_encoding_header_test.dart
> +      'when a Transfer-Encoding header with an invalid value is passed '
Question: Why was a test removed in this commit? https://github.com/serverpod/relic/pull/17/commits/c95c70c67e89d0e184945a0407f586172299e9f6

2025-01-09 13:32 UTC, klkucaj commented on lib/src/headers/headers.dart
> +    for (var entry in booleanHeaders.entries) {
We don’t need that because we already have tests covering all headers. I added this specifically because the tests for this header were failing. Previously, these tests were failing along with many others due to the transfer encoding and content length issue. Now that the issue has been resolved and merged, I had a clearer understanding of what needed to be fixed and what was already addressed in the other ticket.

2025-01-09 13:38 UTC, klkucaj commented on lib/src/relic_server.dart
> +      return Response.badRequest(
yes, done

2025-01-09 13:40 UTC, klkucaj commented on lib/src/headers/headers.dart
> +    // Failed headers to parse
Now this depends, `invalidHeaders` is a good naming but also `failedHeadersToParse` tells we failed to parse these headers, but still i am not sure, what do you suggest ?

2025-01-09 13:47 UTC, klkucaj commented on lib/src/relic_server.dart
> -      await errorResponse.writeHttpResponse(
Nope it was not dead code, check this:
Before:
https://github.com/serverpod/relic/blob/e2607bc2244bea41867f64c2971714416df9b407/lib/src/relic_server.dart#L143-L163

After:
https://github.com/klkucaj/relic/blob/fdd40a728760f4fe5559d8a000038c0f75e0cc3d/lib/src/relic_server.dart#L141-L170


Previously, we created the response first and then wrote it. Now, we handle each condition individually as we write the response.

2025-01-09 13:51 UTC, klkucaj commented on test/headers/typed_headers/transfer_encoding_header_test.dart
> +      'when a Transfer-Encoding header with an invalid value is passed '
I remove this:
https://github.com/serverpod/relic/blob/e2607bc2244bea41867f64c2971714416df9b407/test/headers/typed_headers/transfer_encoding_header_test.dart#L76-L89

because its basically same as this:
https://github.com/serverpod/relic/blob/e2607bc2244bea41867f64c2971714416df9b407/test/headers/typed_headers/transfer_encoding_header_test.dart#L57-L74

Should i add it back ?

2025-01-09 14:30 UTC, klkucaj commented on lib/src/relic_server.dart
> +    } on InvalidHeaderException catch (error) {
Check this commit and let me know: https://github.com/serverpod/relic/pull/17/commits/de47c92c2626827d348d508d76b6f6367528c0c3

2025-01-09 15:10 UTC, SandPod commented on lib/src/headers/headers.dart
> +  }) {
This has not been fixed.

2025-01-09 15:12 UTC, SandPod commented on lib/src/headers/headers.dart
> +    for (var entry in booleanHeaders.entries) {
If a header is added but forgotten to be added to any of the maps. Would some form of test catch that? Like a response request test or something?

2025-01-09 15:14 UTC, klkucaj commented on lib/src/headers/headers.dart
> +  }) {
Done

2025-01-09 15:14 UTC, SandPod commented on test/headers/typed_headers/transfer_encoding_header_test.dart
> +      'when a Transfer-Encoding header with an invalid value is passed '
To me, these tests seems to serve different purposes. They have different configuration. The one bellow validates that the entries are sorted correctly. The top one does not take that into consideration for its validation. Is there any other test that you consider overlaps with the top one? Otherwise, I don't think this motivates removing the test.

2025-01-09 15:17 UTC, SandPod requested changes

2025-01-09 15:17 UTC, SandPod commented on test/exception/relic_exceptions_test.dart
> +      await _scheduleServer((Request request) => throw HijackException());
Question: Isn't the purpose of the Hijack exception to take over what happens with the request?

2025-01-09 15:17 UTC, SandPod commented on test/exception/relic_exceptions_test.dart
> +        'then it returns a 400 Bad Request response', () async {
Suggestion: Change to `then it returns a 400 Bad Request response with exception message included in body.`

2025-01-09 15:18 UTC, klkucaj commented on lib/src/headers/headers.dart
> +    for (var entry in booleanHeaders.entries) {
If a new header is added without including the corresponding test for the header, it will not be detected. Unfortunately, there doesn't seem to be a way to avoid this entirely. The key idea is that whenever a header is added, it must also be included in the map.

2025-01-09 15:19 UTC, klkucaj commented on test/headers/typed_headers/transfer_encoding_header_test.dart
> +      'when a Transfer-Encoding header with an invalid value is passed '
I think its better to add it back.

2025-01-09 15:26 UTC, klkucaj commented on test/exception/relic_exceptions_test.dart
> +      await _scheduleServer((Request request) => throw HijackException());
Yes, that's correct. However, when you take over (hijack) a request, you should not attempt to write it back as a response. Instead, you need to manage the socket stream directly to write, read, or close the connection as needed.

2025-01-10 07:49 UTC, SandPod requested changes

2025-01-10 07:49 UTC, SandPod commented on lib/src/headers/headers.dart
> +    for (var entry in booleanHeaders.entries) {
Could you file an issue for this? I think this can be solved by simply providing a way to retrive all the headers from `toMap` without filtering out the null values.
But we would also need to have a way to automatically iterate all of the header constants.

2025-01-10 07:49 UTC, SandPod commented on lib/src/relic_server.dart
> +        body: Body.fromString(error.toString()),
Suggestion: Add a different field to the `InvalidHeaderException` that is used to build the body of the request.

The purpose of this is to clearly differentiate between internal bug messages compared to what we send to the client.

2025-01-10 07:49 UTC, SandPod commented on lib/src/relic_server.dart
>      if (!relicRequest.canHijack) {
Question: When do we end up in this case? Don't we already handle the hijack above? Feels like this will hit as soon as you disable hijack in for relic requests?

2025-01-10 07:49 UTC, SandPod commented on test/exception/relic_exceptions_test.dart
> +      await _scheduleServer((Request request) => throw HijackException());
But this only happens if hijack is disabled right? If it is enabled we shouldn't throw if I understand the code correctly? So that should be reflected in the given and part of the setup for the test.

2025-01-10 10:54 UTC, klkucaj commented on lib/src/relic_server.dart
>      if (!relicRequest.canHijack) {
Fixed!

2025-01-10 13:34 UTC, SandPod commented on lib/src/headers/headers.dart
> +  final _LazyInit<DateTime?> _ifUnmodifiedSince;
Comment: This is a feature that should have been added in a different PR. It has nothing to do with lazy loading.

But keep it now.

2025-01-10 13:34 UTC, SandPod commented on lib/src/extensions/http_response_extension.dart
> +      if (value != null) {
Question/Discussion: Now we will always filter out `null` custom headers as well, restricting the flexibility of the users of this interface. Do we really want to do that?

2025-01-10 13:34 UTC, SandPod commented on lib/src/headers/headers.dart
> +    bool allowNullValueToBeIncluded = false,
Suggestion: This only applies to managed headers. Please update the message and variable name accordingly.

2025-01-10 13:34 UTC, SandPod commented on test/headers/header_test.dart
> +      expect(map.containsKey('age'), isFalse);
Comment: This needs an explanation, why does this key not being present imply that null values are excluded? Update the description.

2025-01-10 13:34 UTC, SandPod commented on test/headers/header_test.dart
> +    test(
Suggestion: For these tests, part of the given is that we have a headers class that does not have any headers added to it. I suggest you break this out into a separate group so that this is clear.

2025-01-10 13:34 UTC, SandPod commented on lib/src/relic_server.dart
> +        'after the request has been hijacked.',
Suggestion: Remove the last part since that doesn't make us end up here right? `Ensure you dont attempt to write to the HTTP after the request has been hijacked.`.

And give a proper error message to why we ended up here, same as described above. We are missing an expected throw with a `HijackException`.

2025-01-10 13:34 UTC, SandPod commented on test/hijack/relic_hijack_test.dart
> +library;
Question: Are these required? We don't test on any other platform right?

2025-01-10 13:34 UTC, SandPod commented on test/hijack/relic_hijack_test.dart
> +        'to the HTTP response', () async {
Suggestion: Shouldn't we respond with a 500 here as well?

2025-01-10 13:57 UTC, klkucaj commented on lib/src/extensions/http_response_extension.dart
> +      if (value != null) {
This is needed because set method does not accept null values.

2025-01-10 14:48 UTC, klkucaj commented on test/hijack/relic_hijack_test.dart
> +library;
Removed all

2025-01-10 15:03 UTC, SandPod commented on test/headers/header_test.dart
> +                // managed by the body class and applied later to the response.
Suggestion: Include this in the description of the test.

2025-01-10 15:03 UTC, SandPod commented on test/headers/header_test.dart
> +                // managed by the body class and applied later to the response.
when converting to map then all configurable managed headers are included.

2025-01-10 16:07 UTC, SandPod commented on test/headers/header_test.dart
> +      test('then no unexpected additional headers are included', () {
```suggestion
      test('then only managed headers are included.', () {
```

2025-01-10 16:13 UTC, klkucaj commented on test/headers/header_test.dart
> +                  header != Headers.contentTypeHeader,
yes

2025-01-10 16:21 UTC, SandPod approved these changes

2025-01-10 16:42 UTC, merged