fix: Resolve Content-Length header conflict with Transfer-Encoding: chunked
serverpod/relic pull request #22
Opened 2024-12-18 13:36 UTC by klkucaj

This PR resolves an issue where `Content-Length` was incorrectly included alongside `Transfer-Encoding: chunked`, violating the HTTP/1.1 specification (RFC 7230). 

**Fixes Implemented:**
- Removed `Content-Length` when `Transfer-Encoding: chunked` is applied.
- Ensured `Content-Length` is only included for other valid `Transfer-Encoding` values (e.g., gzip, deflate).
- Added logic to reorder transfer encodings, ensuring `chunked` is always the last encoding.

**Impact:**
This fix ensures compliance with HTTP/1.1, preventing ambiguity and avoiding potential protocol errors in HTTP clients and servers.

**Closes:** #20

2025-01-02 12:03 UTC, SandPod requested changes
I know a lot of digging went into this one so it will be nice to get this resolved.

I had a couple of comments and suggestion. Maybe we could have a call if anything is unclear.

2025-01-02 12:03 UTC, SandPod commented on test/relic_server_serve_test.dart
> +      expect(response.body, equals('2\r\nhi\r\n0\r\n\r\n'));
Suggestion: Could you clarify the description on this test so that it is clear what and why we do this validation?

2025-01-02 12:03 UTC, SandPod commented on test/message/body_test.dart
> +      expect(response.headers['transfer-encoding'], contains('chunked'));
Suggestion: Use `TransferEncoding.chunked` in the validation for the tests.

2025-01-02 12:03 UTC, SandPod commented on test/message/body_test.dart
> +      expect(response.headers['transfer-encoding'], contains('chunked'));
Use this for all tests when referring to any header string.

2025-01-02 12:26 UTC, klkucaj commented on test/headers/headers_test_utils.dart
> +        headers: echoHeaders ? parsedHeaders : null,
No, there's no difference. Whether you explicitly set `headers` to `null` or just call `Response.ok()` without modifying it, the outcome is the same. The constructor handles it like this:  

```dart
...
headers: headers ?? Headers.response(),
...
```

This means if `headers` is `null`, it will default to `Headers.response()`.

2025-01-02 12:30 UTC, klkucaj commented on lib/src/headers/typed/headers/transfer_encoding_header.dart
> +    if (chunked == null) return encodings;
The reason I used `firstWhereOrNull` instead of `.contains` is that `.contains` only works directly with primitive types or objects that have properly overridden the `==` operator and `hashCode`. 
In this case, since `TransferEncoding` is a custom class and doesn’t inherently support those overrides, `.contains` wouldn’t work out of the box without additional implementation.

By using `firstWhereOrNull`, I can avoid the need to override `==` and `hashCode`, and directly match based on a specific property (`name` in this case), which keeps the logic simple and avoids unnecessary changes to the `TransferEncoding` class.

2025-01-02 12:44 UTC, klkucaj commented on lib/src/headers/headers.dart
> +  void applyHeaders(io.HttpResponse response) {
Yes, you are right!

2025-01-02 15:35 UTC, SandPod reviewed
Couple of more comment and suggestion.

2025-01-02 15:35 UTC, SandPod commented on lib/src/body/types/mime_type.dart
> +  static const multipart = MimeType('multipart', 'form-data');
Suggestion: Rename to `formData`.

Following the naming used above i would expect this to be named form data? What does dart use?

2025-01-02 15:35 UTC, SandPod commented on lib/src/body/types/mime_type.dart
> +  static const multipartByteranges = MimeType('multipart', 'byteranges');
Suggestion: Following how `plainText` is named, this should probably be named `byterangesMultipart` right? What does dart call these?

2025-01-02 15:35 UTC, SandPod commented on lib/src/body/types/mime_type.dart
> +  bool get isMultipartByteranges {
Suggestion: If this is only used in a single place, do the check there directly insteaaed of adding an extention.

2025-01-02 15:35 UTC, SandPod commented on lib/src/body/body.dart
> +import 'package:relic/relic.dart';
Question: This file now only contains a change to this import, is this required?

2025-01-02 15:35 UTC, SandPod commented on lib/src/extensions/http_response_extension.dart
> +        ..contentLength = body.contentLength!
Suggestion: Assign the content length before nullcheck so that the dangerous derreff can be avoided ( `!`)

2025-01-02 15:35 UTC, SandPod commented on lib/src/extensions/http_response_extension.dart
> +    var httpHeaders = this.headers;
Suggestion: Rename to `responseHeaders` to make it clear what this is.

2025-01-02 15:35 UTC, SandPod commented on lib/src/extensions/http_response_extension.dart
> +      var value = entry.value;
Suggestion(NIT): Skip assigning this variable and just pass it directly to the set method.

`httpHeaders.set(entry.key, entry.value);`

2025-01-02 15:35 UTC, SandPod commented on lib/src/extensions/http_response_extension.dart
> +      httpHeaders.contentLength = 0;
Question: If we don't use chunked encoding, shouldn't this be the correct content length?

2025-01-02 15:35 UTC, SandPod commented on test/relic_server_serve_test.dart
> +              contentLength: 4,
No reply and no fix to this comment, Please look at it again.

2025-01-02 15:48 UTC, klkucaj commented on lib/src/extensions/http_response_extension.dart
> +      httpHeaders.contentLength = 0;
Your right.

2025-01-03 08:20 UTC, klkucaj commented on lib/src/body/body.dart
> +import 'package:relic/relic.dart';
I am going to revert this to main because there no need to do any changes here, the reason why is only this because this is how it is on main https://github.com/klkucaj/relic/blob/c4a9eedd99636336dbf2ce7338b1ccb574d4205b/lib/src/body/body.dart#L6-L7

2025-01-03 08:34 UTC, klkucaj commented on test/relic_server_serve_test.dart
> +              contentLength: 4,
Yes u are right, sorry, i improved other tests and i missed this.

2025-01-03 08:43 UTC, klkucaj commented on lib/src/body/types/mime_type.dart
> +  static const multipartByteranges = MimeType('multipart', 'byteranges');
@SandPod check the new version of mime type and let me know if its okay.

2025-01-03 13:17 UTC, SandPod commented on test/message/body_test.dart
> +        'with a valid content length when applying headers '
Suggestion: Add a line break for each section in the `Given, When, Then` pattern.

This should be applied to all tests in this file.

For this test that would result in:

```dart
'with a valid content length '
'when applying headers to the response '
'then Content-Length is used instead of chunked encoding'
```

2025-01-03 13:17 UTC, SandPod commented on test/message/body_test.dart
> +                  ]),
Question: What happens if no data is returned from the stream?

2025-01-03 13:17 UTC, SandPod commented on lib/src/extensions/http_response_extension.dart
> +    var bodyMimeType = body.contentType?.mimeType;
Question: What is the difference between `body.contentType` and `body.getContentType`?

2025-01-03 13:17 UTC, SandPod commented on lib/src/extensions/http_response_extension.dart
> +    if (shouldEnableChunkedEncoding && !isChunked) {
Discussion: This still looks a bit funky to me. Let's discuss it.

2025-01-07 13:33 UTC, klkucaj commented on lib/src/extensions/http_response_extension.dart
> +    var bodyMimeType = body.contentType?.mimeType;
Renamed `body.contentType` to `body.bodyType`, this is our implementation of `contentType`.

2025-01-07 13:48 UTC, klkucaj commented on test/message/body_test.dart
> +                  ]),
This is removed now, we dont need it anymore.

2025-01-08 10:56 UTC, SandPod commented on lib/src/extensions/http_response_extension.dart
> +  /// Resolves conflicts between `Content-Length` and `Transfer-Encoding`
Suggestion: Clarify this comment. We no longer resolve conflicts but simply add the the chunked header if required by the body.

2025-01-08 10:56 UTC, SandPod commented on lib/src/extensions/http_response_extension.dart
> +  /// Resolves conflicts between `Content-Length` and `Transfer-Encoding`
Combine this with the comment above as well.

2025-01-08 10:56 UTC, SandPod commented on lib/src/headers/typed/headers/transfer_encoding_header.dart
> +  bool get isIdentity {
Suggestion: Is `isChunked` and `isIdentity` only used in apply headers? If so, these could be extensions there instead of bloating this class.

2025-01-08 10:56 UTC, SandPod commented on lib/src/message/message.dart
> +  /// Returns the MIME type from the Body-Type (Content-Type) header, if available.
Suggestion: Should `header` be inside of the `)` as well?

2025-01-08 10:56 UTC, SandPod commented on lib/src/message/response.dart
> +  /// {@macro relic_response_body_and_encoding_param}
Question: What is the macro here?

2025-01-08 10:56 UTC, SandPod commented on test/relic_server_serve_test.dart
> +    test('is added when the transfer-encoding header is unset', () async {
Suggestion: The description here doesn't really explain the difference in the tests here. The important part is that we don't have a content length in order for the chunked to be added.

2025-01-08 10:56 UTC, SandPod commented on test/relic_server_serve_test.dart
> +    test('is added when the transfer-encoding header is unset', () async {
Same for the other tests in this group.

2025-01-08 10:56 UTC, SandPod commented on test/message/body_test.dart
> +void main() {
Question: Are these the same as the tests in `relic_server_serve_test`?

2025-01-08 11:13 UTC, klkucaj commented on lib/src/message/response.dart
> +  /// {@macro relic_response_body_and_encoding_param}
A way to share comments that are only written in one place.

2025-01-08 15:10 UTC, klkucaj commented on test/message/body_test.dart
> +void main() {
Fixed!

2025-01-08 15:17 UTC, klkucaj commented on test/relic_server_serve_test.dart
> +    test('is added when the transfer-encoding header is unset', () async {
I updated some of the tests, moving a portion to `apply_headers_test.dart`. However, I didn't update the others as they were directly imported from Shelf. I'm unsure if updating these is necessary at this point.
What do u suggest ?

2025-01-09 08:31 UTC, SandPod reviewed
Last fix!

2025-01-09 08:31 UTC, SandPod commented on test/message/apply_headers_test.dart
> +  group('Given a response', () {
Suggestion(NIT): For clarity: `Given a framework response object with some headers when applying headers to http response then headers are applied correctly`?

2025-01-09 08:31 UTC, SandPod commented on test/message/apply_headers_test.dart
> +void main() {
Suggestion: We are missing one test here now right, the test when we actually add the transfer chunked encoded? When content-lenght = null.

2025-01-09 08:48 UTC, klkucaj commented on test/message/apply_headers_test.dart
> +  group('Given a response', () {
Done

2025-01-09 09:25 UTC, SandPod approved these changes
LGTM! 👍

2025-01-09 09:25 UTC, merged