refactor: Replace Object usage with strongly-typed implementations
serverpod/relic pull request #24
Opened 2024-12-23 10:32 UTC by klkucaj

### PR Description
This PR replaces instances of `Object` with strongly-typed implementations to improve code clarity, maintainability, and type safety. 

Key changes include:
- Introducing `RelicAddress` to encapsulate address and port handling.
- Refactoring tests to use the new `createServer` helper for consistent server setup.

No functional changes were made; this is purely a refactor for improved code quality.

2025-01-02 12:43 UTC, SandPod requested changes
Nice cleanup for the tests. Couple of suggestions to improve the solution and remove some unecessary if, checks.

2025-01-02 12:43 UTC, SandPod commented on lib/src/address/relic_address.dart
> +  Object get address => hostname ?? internetAddress!;
Suggestion: Make this into two distinct types (Classes) that inherit from RelicAddress.

One that is a wrapper for InternetAddress and one that is a wrapper around a String address.

2025-01-02 12:43 UTC, SandPod commented on lib/src/address/relic_address.dart
> +  final int port;
Suggestion/Discussion: Remove `port` from the address.

These aren't really connected so could keep them separate.

2025-01-02 12:43 UTC, SandPod commented on lib/src/address/relic_address.dart
> +  final int port;
I would expect them to possibly change independently as well.

2025-01-02 12:43 UTC, SandPod commented on lib/src/relic_server.dart
>            securityContext!,
Is it possible to remove the `!` here?

2025-01-02 12:43 UTC, SandPod commented on lib/src/address/relic_address.dart
> +  final InternetAddress? internetAddress;
Question: Should we export this?

2025-01-02 12:43 UTC, SandPod commented on test/relic_server_serve_test.dart
>      request.sink.close();
Suggestion: Can't you wrap this in an `unawaited`?

2025-01-02 12:43 UTC, SandPod commented on test/headers/headers_test_utils.dart
> +Future<RelicServer> createServer({
Comment: Nice cleanup 🌟

2025-01-02 12:48 UTC, klkucaj commented on test/relic_server_serve_test.dart
>      request.sink.close();
No, i tried but i got all red https://github.com/serverpod/relic/actions/runs/12580646629/job/35062957328

2025-01-02 14:50 UTC, klkucaj commented on lib/src/address/relic_address.dart
> +  final InternetAddress? internetAddress;
yes, done

2025-01-02 14:51 UTC, klkucaj commented on lib/src/relic_server.dart
>            securityContext!,
yes!

2025-01-02 15:45 UTC, SandPod commented on lib/src/address/relic_address.dart
> +abstract class RelicAddress<T> {
Suggestion: Please add static methods to create the different type of Relic addresses.

Then the users of the interface do not need to know the different types directly.

2025-01-02 15:45 UTC, SandPod commented on lib/src/address/relic_address.dart
> +  final InternetAddress? internetAddress;
Shouldn't we export `InternetAddress` as well? so that it is enough to import the relic package without having to import the http package?

2025-01-02 15:45 UTC, SandPod commented on lib/src/address/relic_address.dart
> +abstract class RelicAddress<T> {
`fromHostname` and `fromInternetAddress`.

2025-01-03 08:46 UTC, klkucaj commented on lib/src/address/relic_address.dart
> +  final InternetAddress? internetAddress;
yes!

2025-01-03 08:50 UTC, klkucaj commented on lib/src/address/relic_address.dart
> +abstract class RelicAddress<T> {
done

2025-01-03 10:05 UTC, SandPod approved these changes
LGTM! 👍

2025-01-03 10:06 UTC, merged